회원 가입 기능 추가
f-lab-edu/Bridge_SNS pull request #2
Opened 2023-03-06 18:06 UTC by hobulian

회원 가입에 대한 기능을 생성했습니다.

2023-03-06 18:51 UTC, f-lab-TJ commented
1. Commit 메세지 body에 더 상세한 내용을 적어주세요. (어떤 것을 변경했는지, 어떤 것이 추가되었는지, test는 어떻게 수행하였는지.
2. Test code가 없습니다. Unit test를 추가해주세요.

2023-03-06 18:52 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +    @GetMapping("/checkDuplicated")
boolean을 리턴하는 함수이니 isDuplicated 는 어떨까요?

2023-03-06 18:53 UTC, f-lab-TJ commented on src/main/java/com/sns/model/Member.java
> +    private String profile_image;
profile_imagepath와 차이점이 뭔가요?

2023-03-06 18:54 UTC, f-lab-TJ commented on src/main/java/com/sns/model/Member.java
> +    private String profile_name;
이름이 없는 경우 빈칸으로 두나요, default 값을 DB에 저장하나요?

2023-03-06 21:14 UTC, f-lab-TJ commented on src/main/java/com/sns/model/Member.java
> +    private Date joindate;
해당 아이템은 서버에서 추가하기로 했던 것 같은데, 로직 추가해봅시다.

2023-03-06 21:14 UTC, hobulian commented on src/main/java/com/sns/controller/MemberController.java
> +    @GetMapping("/checkDuplicated")
그게 좀 더 직관적일 것 같습니다. 확인했어요.

2023-03-06 21:15 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +        boolean isDuplicated = (memberService.checkDuplicatedMember(id) == 1);
유저가 지정한 id를 id로 사용해도 아무런 문제가 없을까요? 유저 id와 별개로 직접 generate한 id를 사용하면 여러가지 장점이 있을 수 있는데, 한번 고민해보면 좋을 것 같습니다.

2023-03-06 21:16 UTC, hobulian commented on src/main/java/com/sns/model/Member.java
> +    private String profile_image;
image는 파일이름이고 imagepath는 파일이 저장되는 경로로 설정했습니다. 지금 생각해보니 파일을 어떻게 어디에 저장할지 부분이 좀 이해가 부족한듯 해서 좀 더 알아보겠습니다.

2023-03-06 21:16 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +        memberService.addMember(member);
`checkDuplicated` 후 `signup`하는 것으로 보이는데, 만약 이 두 함수 사이 다른 사람이 해당 id를 선점하면 어떻게 되는 것일까요?

2023-03-06 21:17 UTC, hobulian commented on src/main/java/com/sns/model/Member.java
> +    private String profile_name;
원래는 빈 칸으로 두기로 했는데, 입력되지 않으면 id와 동일한 값을 저장하는 것도 방법인 듯 합니다.

2023-03-06 21:18 UTC, f-lab-TJ commented on src/main/java/com/sns/config/MybatisConfig.java
> +@Lazy
해당 annotation은 왜 사용하였나요?

2023-03-06 21:24 UTC, hobulian commented on src/main/java/com/sns/config/MybatisConfig.java
> +@Lazy
해당 설정들을 lazy initialization하여 애플리케이션 초기 실행 시 성능을 올릴 수 있다고 생각해서 사용했습니다.

2023-03-06 21:26 UTC, hobulian commented on src/main/java/com/sns/model/Member.java
> +    private Date joindate;
database에는 추가된 시간으로 들어가게끔 되어있긴 한데, getter 메소드로 가입 시간을 조회하려 할 떄 필요할 듯 해서 변수로 지정해놓았습니다.

2023-03-06 21:35 UTC, hobulian commented on src/main/java/com/sns/controller/MemberController.java
> +        memberService.addMember(member);
해당 사항에 대해서 생각해보지 못했네요. 우선 db는 id에 중복 값이 insert되는 것을 허용하고 있지 않기 때문에 SQLException이 발생할 듯 합니다.

2023-03-11 16:05 UTC, hobulian commented
> 

단위 테스트 작성에 발생한 문제 해결에 시간이 다소 소요되어서 일단 다른 부분들 먼저 수정해서 커밋하였습니다.

2023-03-12 17:57 UTC, f-lab-TJ requested changes

2023-03-12 17:57 UTC, f-lab-TJ commented on src/main/resources/application.yml
> +spring:
하나의 pull request에는 하나의 피쳐만 존재해야합니다. 다른 피쳐나 설정파일의 경우 몇줄짜리 수정이더라도 pull request를 따로 만드시기 바랍니다.

2023-03-12 17:57 UTC, f-lab-TJ commented on bridge_sns_alarm.sql
> +CREATE DATABASE  IF NOT EXISTS `bridge_sns` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */;
DB 스키마도 다른 pull request로 빼 두도록 합시다.

2023-03-12 17:57 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +        } else {
이와 같은 코드 패턴에서 else가 필요할까요?
코드 간결성을 최대한 높이기 위해서 불필요한 else를 줄여 code depth를 줄이도록 합시다.

2023-03-12 17:57 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +    private String generateUniqueId() { // 서버측에 저장할 Unique ID를 DB에서 겹치지 않을 때까지 재귀적으로 생성
코멘트와 다르게 재귀적으로 id를 생성하지 않는 것 같습니다.
또, generateUniqueId와 같은 query를 보내는 대신 SQL query를 통해 중복시 insert에 실패하도록 할 수 있는데, 확인해보면 좋을 것 같습니다.

2023-03-12 17:57 UTC, f-lab-TJ commented on bridge_sns_alarm.sql
> +CREATE DATABASE  IF NOT EXISTS `bridge_sns` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */;
새로 pull request를 만들면 그곳에 코멘트 작성하도록 하겠습니다.

2023-03-19 18:06 UTC, f-lab-TJ requested changes

2023-03-19 18:06 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +        memberService.addMember(member);
DB add 가 실패한 경우 에러처리도 해야하지 않을까요?

2023-03-19 18:06 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +        memberService.addMember(member);
user id 가 20글자를 넘는 경우는 어떻게 되나요?

2023-03-19 18:06 UTC, f-lab-TJ commented on src/main/resources/application.yml
> +spring:
여전히 application.yml 파일이 해당 pull request에 존재하네요.

2023-03-19 18:06 UTC, f-lab-TJ commented on src/main/java/com/sns/controller/MemberController.java
> +                        throw e;
유저에게 노출되는 모든 API는 적절하게 error handling 되어 반환되어야 합니다. 에러를 바로 throw하는 경우, 서버의 디버깅 로그가 사용자에게 전달되는 등의 이슈가 발생할 수 있습니다.

2023-03-20 16:35 UTC, hobulian reviewed
자잘하게 커밋을 나눴어야 했는데 좀 여러가지 기능들이 한 번에 들어가서 Revert한 뒤에 나눠서 커밋하였습니다.

2023-03-21 04:58 UTC, f-lab-TJ approved these changes

2023-03-21 04:58 UTC, f-lab-TJ commented on src/main/java/com/sns/exceptions/Handler.java
> +
log4j등을 이용한 로그도 추가해주도록 합시다.

2023-03-21 04:59 UTC, f-lab-TJ approved these changes

2023-03-24 23:00 UTC, f-lab-TJ commented
Approve를 하였는데 github에서는 Review required로 뜨네요. github 설정을 한번 확인해보고, 머지해서 올려보도록 합시다.

2023-03-26 13:48 UTC, merged